---
title: "TADPOLE_COMPARISON"
author: "Jose Tamez"
date: "`r Sys.Date()`"
output: 
  html_document: 
    toc: yes
    fig_caption: yes
    number_sections: yes
  word_document: 
    reference_docx: WordStyle_FRESA.docx
    toc: yes
    fig_caption: yes
editor_options:
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(collapse = TRUE, warning = FALSE, message = FALSE,comment = "#>")
```

# TADPOLE and ROC PLOTS

### Loading the libraries

```{r}
library("FRESA.CAD")
library(survival)
library(readxl)
library(igraph)
op <- par(no.readonly = TRUE)
pander::panderOptions('digits', 3)
pander::panderOptions('table.split.table', 400)
pander::panderOptions('keep.trailing.zeros',TRUE)

```

## Loading ALL Results

```{r  results = "asis", warning = FALSE, dpi=600, fig.height= 6.0, fig.width= 8.0}
load("~/GitHub/SurvivalTadpole/RMDS/TADPOLE_BESS_Results.RData")
load("~/GitHub/SurvivalTadpole/RMDS/TADPOLE_LASSO_Results.RData")
load("~/GitHub/SurvivalTadpole/RMDS/TADPOLE_BSWIMS_Results.RData")


par(op)


survmtest <- cvLASSORaw$survMedianTest
survmtest <- survmtest[complete.cases(survmtest),]
prBinLASSO <- predictionStats_binary(survmtest[,c(2,3)],"LASSO: MCI to  AD Conversion")

survmtest <- cvRIDGERaw$survMedianTest
survmtest <- survmtest[complete.cases(survmtest),]
prBinRIDGE <- predictionStats_binary(survmtest[,c(2,3)],"RIDGE: MCI to  AD Conversion")

survmtest <- cvBESSRaw$survMedianTest
survmtest <- survmtest[complete.cases(survmtest),]
prBinBESS <- predictionStats_binary(survmtest[,c(2,3)],"BESS:BIC: MCI to  AD Conversion")

survmtest <- cvBESSERaw$survMedianTest
survmtest <- survmtest[complete.cases(survmtest),]
prBinBESSEBIC <- predictionStats_binary(survmtest[,c(2,3)],"BESS:EBIC: MCI to  AD Conversion")

survmtest <- cvBESSGSERaw$survMedianTest
survmtest <- survmtest[complete.cases(survmtest),]
prBinBESSGS <- predictionStats_binary(survmtest[,c(2,3)],"BESS:GS: MCI to  AD Conversion")

survmtest <- cvBSWiMSRaw$survMedianTest
survmtest <- survmtest[complete.cases(survmtest),]

prBinBSWiMS <- predictionStats_binary(survmtest[,c(2,3)],"MCI to  AD Conversion")


par(new=TRUE)
plot(prBinLASSO$ROC.analysis$roc.predictor,col="red")
par(new=TRUE)
plot(prBinRIDGE$ROC.analysis$roc.predictor,col="pink")
par(new=TRUE)
plot(prBinBESS$ROC.analysis$roc.predictor,col="blue")
par(new=TRUE)
plot(prBinBESSEBIC$ROC.analysis$roc.predictor,col="cyan")
par(new=TRUE)
plot(prBinBESSGS$ROC.analysis$roc.predictor,col="gold")
legend("bottomright",
       legend=c("BSWiMS","LASSO","RIDGE","BIC","EBIC","GS"),
       lty=1,
       col=c("black","red","pink","blue","cyan","gold"),cex=0.85)


```

### ROC Tests
```{r}
pander::pander(roc.test(prBinLASSO$ROC.analysis$roc.predictor,prBinBSWiMS$ROC.analysis$roc.predictor))
pander::pander(roc.test(prBinLASSO$ROC.analysis$roc.predictor,prBinBESSEBIC$ROC.analysis$roc.predictor))
pander::pander(roc.test(prBinLASSO$ROC.analysis$roc.predictor,prBinBESSGS$ROC.analysis$roc.predictor))
pander::pander(roc.test(prBinLASSO$ROC.analysis$roc.predictor,prBinBESS$ROC.analysis$roc.predictor))
pander::pander(roc.test(prBinLASSO$ROC.analysis$roc.predictor,prBinRIDGE$ROC.analysis$roc.predictor))

pander::pander(roc.test(prBinBSWiMS$ROC.analysis$roc.predictor,prBinBESSEBIC$ROC.analysis$roc.predictor))
pander::pander(roc.test(prBinBSWiMS$ROC.analysis$roc.predictor,prBinBESSGS$ROC.analysis$roc.predictor))
pander::pander(roc.test(prBinBSWiMS$ROC.analysis$roc.predictor,prBinBESS$ROC.analysis$roc.predictor))
pander::pander(roc.test(prBinBSWiMS$ROC.analysis$roc.predictor,prBinRIDGE$ROC.analysis$roc.predictor))


```

## Summary tables


### MCI to Dementia table
```{r}

selFeatures <- names(cvBSWiMSRaw$featureFrequency[cvBSWiMSRaw$featureFrequency>5])

clusterFeatures <- fc$names


tableMCI_to_Dem <- sm$coefficients[clusterFeatures,
                                   c("Estimate",
                                     "lower",
                                     "HR",
                                     "upper",
                                     "full.AUC",
                                     "Delta.AUC",
                                     "z.IDI",
                                     "Frequency")]

nugget <- fc$membership
names(nugget) <- clusterFeatures

tableMCI_to_Dem$Cluster <- nugget[rownames(tableMCI_to_Dem)]
tableMCI_to_Dem$CVFreq <- cvBSWiMSRaw$featureFrequency[clusterFeatures]

rnames <- clusterFeatures[str_detect(clusterFeatures,"ST")]
frnames <- rnames
rnames <- str_replace_all(rnames,"M_","")
rnames <- str_replace_all(rnames,"RD_","")
rnames <- str_replace_all(rnames,"Ba_","")
rnames <- str_replace_all(rnames,"De_","")
description <- character()

for (ddet in c(1:length(rnames)))
{
  description <- c(description,TADPOLE_D1_D2_Dict$TEXT[str_detect(TADPOLE_D1_D2_Dict$FLDNAME,rnames[ddet])][1])
}
names(description) <- frnames

tableMCI_to_Dem$Description <- description[rownames(tableMCI_to_Dem)]
pander::pander(tableMCI_to_Dem)


```

### Heat map

```{r results = "asis", warning = FALSE, dpi=600, fig.height= 6.0, fig.width= 8.0}

hm <- heatMaps(Outcome="status",data=TADPOLECrossMRI[,c("status",clusterFeatures)],title="Heat Map",Scale=TRUE,
					   theFiveColors=c("black","red","orange","yellow","white"),
#					   theFiveColors=c("darkred","red","yellow","blue","darkblue"),
					   hCluster="col",
					   cexRow=0.50,cexCol=0.65,srtCol=35,
					   ylab="Subjects",
					   xlab="Features"
					   )

```


### Heat map

```{r results = "asis", warning = FALSE, dpi=600, fig.height= 6.0, fig.width= 8.0}

hm <- heatMaps(Outcome="status",data=TADPOLECrossMRI,title="Heat Map",Scale=TRUE,
					   theFiveColors=c("black","red","orange","yellow","white"),
#					   theFiveColors=c("darkred","red","yellow","blue","darkblue"),
					   hCluster="col",
					   cexRow=0.50,cexCol=0.5,srtCol=35,
					   ylab="Subjects",
					   xlab="Features"
					   )

```

## Feature Analysis

```{r}

fs <- bConvml$bagging$frequencyTable
barplot(fs[order(-fs)],las=2,main="Selected Features",cex.names = 0.5)
sm <- summary(bConvml)
summary(TADPOLE_Conv_TRAINNorm$M_ST39CV)
pander::pander(bConvml$formula.list)
pander::pander(bConvml$bagging$predfit$coef)
cnames <- names(bConvml$bagging$bagged.model$coefficients)
pander::pander(cbind(
                      bConvml$bagging$bagged.model$coefficients,
                      bConvml$bagging$bagged.model$baggingAnalysis$coefficients[cnames],
                      bConvml$bagging$bagged.model$baggingAnalysis$wts[cnames],
                      bConvml$bagging$bagged.model$baggingAnalysis$avgLogPvalues[cnames],
                      bConvml$bagging$bagged.model$baggingAnalysis$RelativeFrequency[cnames])
)
pander::pander(sm$coefficients)
pander::pander(bConvml$univariate[bConvml$selectedfeatures,])

#ptestl <- predict(bConvml,TADPOLE_Conv_TEST,type="lp")
ptestl <- predict(bConvml,TADPOLE_Conv_TESTNorm,type="lp")
boxplot(ptestl~TADPOLE_Conv_TEST$status)
#ptestr <- predict(bConvml,TADPOLE_Conv_TEST,type="risk")
ptestr <- predict(bConvml,TADPOLE_Conv_TESTNorm,type="risk")
eventCases <- subset(TADPOLE_Conv_TEST,status==1)
plot(1.0/ptestr[rownames(eventCases)]~eventCases$TimeToEvent)
pander::pander(cor.test(eventCases$TimeToEvent,1.0/ptestr[rownames(eventCases)],method="spearman"))



perdsurv <- as.data.frame(cbind(Times=TADPOLE_Conv_TEST$TimeToEvent,
                  Outcome=TADPOLE_Conv_TEST$status,
                  LinearPredictors=ptestl,
                  ptestr))
boxplot(perdsurv$LinearPredictors~perdsurv$Outcome)
prSurv <- predictionStats_survival(perdsurv,"BSWiMS: MCI to  AD Conversion")
pander::pander(prSurv$CIRisk)
pander::pander(prSurv$CILp)
pander::pander(prSurv$spearmanCI)

prBin <- predictionStats_binary(cbind(TADPOLE_Conv_TEST$status,ptestl),"BSWiMS: MCI to  AD Conversion")
pander::pander(prBin$aucs)
pander::pander(prBin$CM.analysis$tab)





par(op)
ho <- mean(TADPOLE_Conv_TRAIN$status)
timeInterval <- mean(TADPOLE_Conv_TRAIN[TADPOLE_Conv_TRAIN$status==0,"TimeToEvent"])
pgzero <- ppoisGzero(perdsurv$LinearPredictors,ho)
rsdata <- cbind(perdsurv$Outcome,pgzero,perdsurv$Times)
riskAnalysis <- RRPlot(rsdata,riskTimeInterval=timeInterval,title="Test")


pander::pander(riskAnalysis$keyPoints)

pander::pander(riskAnalysis$c.index)
pander::pander(riskAnalysis$ROCAnalysis$aucs)
pander::pander(riskAnalysis$cenAUC)
pander::pander(riskAnalysis$ROCAnalysis$ClassMetrics)
pander::pander(riskAnalysis$surdif)

```



### The formula network

```{r results = "asis", warning = FALSE, dpi=600, fig.height= 6.0, fig.width= 8.0}
cmax <- apply(bConvml$bagging$formulaNetwork,2,max)
mcoef <- bConvml$bagging$bagged.model$coefficients
cnames <- names(cmax[cmax>=0.025])
#cnames <- cnames[abs(mcoef[cnames])>1.0e-10]
cmax <- cmax[cnames]
adma <- bConvml$bagging$formulaNetwork[cnames,cnames]

adma[adma<0.15] <- 0;
gr <- graph_from_adjacency_matrix(adma,mode = "undirected",diag = FALSE,weighted=TRUE)
gr$layout <- layout_with_fr

fc <- cluster_optimal(gr)
plot(fc, gr,
     edge.width=5*E(gr)$weight,
     vertex.size=20*cmax,
     vertex.label.cex=0.55,
     vertex.label.dist=0,
     main="MCI to Dementia Conversion")
par(op)

```

