---
title: "TADPOLE_BESS"
author: "Jose Tamez"
date: "`r Sys.Date()`"
output: 
  html_document: 
    toc: yes
    fig_caption: yes
    number_sections: yes
  word_document: 
    reference_docx: WordStyle_FRESA.docx
    toc: yes
    fig_caption: yes
editor_options:
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(collapse = TRUE, warning = FALSE, message = FALSE,comment = "#>")
```

# TADPOLE and BSWiMS

### Loading the libraries

```{r}
library("FRESA.CAD")
library(survival)
library(readxl)
library(igraph)
op <- par(no.readonly = TRUE)
pander::panderOptions('digits', 3)
pander::panderOptions('table.split.table', 400)
pander::panderOptions('keep.trailing.zeros',TRUE)

```

## Loading BSWiMS Results

```{r}

load("./TADPOLE_BSWIMS_Results.RData")

pander::pander(table(TADPOLE_Conv_TRAIN$status))
pander::pander(table(TADPOLE_Conv_TEST$status))
par(op)

```



### Cross Validation BIC

```{r results = "asis", warning = FALSE, dpi=600, fig.height= 6.0, fig.width= 8.0}

cvBESSRaw <- randomCV(TADPOLECrossMRI,
                 Surv(TimeToEvent,status)~.,
                 fittingFunction= BESS,
                 trainSampleSets= cvBSWiMSRaw$trainSamplesSets,
 )

pander::pander(cbind(cvBESSRaw$featureFrequency[cvBESSRaw$featureFrequency>20]))

prBin <- predictionStats_binary(cvBESSRaw$survMedianTrain[,c(2,3)],"TRAIN: MCI to  AD Conversion")

survmtest <- cvBESSRaw$survMedianTest
survmtest <- survmtest[complete.cases(survmtest),]

prBin <- predictionStats_binary(survmtest[,c(2,3)],"BESS:BIC: MCI to  AD Conversion")
pander::pander(prBin$aucs)
pander::pander(prBin$CM.analysis$tab)

par(op)
ho <- mean(survmtest$Outcome)
timeInterval <- mean(survmtest[survmtest$Outcome==0,"Times"])
pgzero <- ppoisGzero(survmtest$LinearPredictorsMedian,ho)
rsdata <- cbind(survmtest$Outcome,pgzero,survmtest$Times)
riskAnalysis <- RRPlot(rsdata,riskTimeInterval=timeInterval,title="BESS:BIC")

riskAnalysis$keyPoints

pander::pander(riskAnalysis$c.index)
pander::pander(riskAnalysis$ROCAnalysis$aucs)
pander::pander(riskAnalysis$cenAUC)
pander::pander(riskAnalysis$ROCAnalysis$ClassMetrics)
pander::pander(riskAnalysis$surdif)

```



### Cross Validation EBIC

```{r results = "asis", warning = FALSE, dpi=600, fig.height= 6.0, fig.width= 8.0}

cvBESSERaw <- randomCV(TADPOLECrossMRI,
                 Surv(TimeToEvent,status)~.,
                 fittingFunction= BESS_EBIC,
                 trainSampleSets= cvBSWiMSRaw$trainSamplesSets,
 )
pander::pander(cbind(cvBESSERaw$featureFrequency[cvBESSERaw$featureFrequency>20]))

prBin <- predictionStats_binary(cvBESSERaw$survMedianTrain[,c(2,3)],"TRAIN: MCI to  AD Conversion")

survmtest <- cvBESSERaw$survMedianTest
survmtest <- survmtest[complete.cases(survmtest),]

prBin <- predictionStats_binary(survmtest[,c(2,3)],"BESS:EBIC: MCI to  AD Conversion")
pander::pander(prBin$aucs)
pander::pander(prBin$CM.analysis$tab)

par(op)
ho <- mean(survmtest$Outcome)
timeInterval <- mean(survmtest[survmtest$Outcome==0,"Times"])
pgzero <- ppoisGzero(survmtest$LinearPredictorsMedian,ho)
rsdata <- cbind(survmtest$Outcome,pgzero,survmtest$Times)
riskAnalysis <- RRPlot(rsdata,riskTimeInterval=timeInterval,title="BESS:EBIC")

pander::pander(riskAnalysis$c.index)
pander::pander(riskAnalysis$ROCAnalysis$aucs)
pander::pander(riskAnalysis$cenAUC)
pander::pander(riskAnalysis$ROCAnalysis$ClassMetrics)
pander::pander(riskAnalysis$surdif)


```

### Cross Validation GS

```{r results = "asis", warning = FALSE, dpi=600, fig.height= 6.0, fig.width= 8.0}

cvBESSGSERaw <- randomCV(TADPOLECrossMRI,
                 Surv(TimeToEvent,status)~.,
                 fittingFunction= BESS_GSECTION,
                 trainSampleSets= cvBSWiMSRaw$trainSamplesSets,
 )
pander::pander(cbind(cvBESSGSERaw$featureFrequency[cvBESSGSERaw$featureFrequency>20]))
prBin <- predictionStats_binary(cvBESSGSERaw$survMedianTrain[,c(2,3)],"TRAIN: MCI to  AD Conversion")

survmtest <- cvBESSGSERaw$survMedianTest
survmtest <- survmtest[complete.cases(survmtest),]

prBin <- predictionStats_binary(survmtest[,c(2,3)],"BESS:GS: MCI to  AD Conversion")
pander::pander(prBin$aucs)
pander::pander(prBin$CM.analysis$tab)

par(op)
ho <- mean(survmtest$Outcome)
timeInterval <- mean(survmtest[survmtest$Outcome==0,"Times"])
pgzero <- ppoisGzero(survmtest$LinearPredictorsMedian,ho)
rsdata <- cbind(survmtest$Outcome,pgzero,survmtest$Times)
riskAnalysis <- RRPlot(rsdata,riskTimeInterval=timeInterval,title="BESS:GS")

pander::pander(riskAnalysis$c.index)
pander::pander(riskAnalysis$ROCAnalysis$aucs)
pander::pander(riskAnalysis$cenAUC)
pander::pander(riskAnalysis$ROCAnalysis$ClassMetrics)
pander::pander(riskAnalysis$surdif)



```

### Learning BIC

```{r results = "asis", warning = FALSE, dpi=600, fig.height= 6.0, fig.width= 8.0}
bConvmBess <- BESS(Surv(TimeToEvent,status)~.,TADPOLE_Conv_TRAIN)

pander::pander(bConvmBess$selectedfeatures)

ptestl <- predict(bConvmBess,TADPOLE_Conv_TEST)
cval <- mean(ptestl)
ptestl <- predict(bConvmBess,TADPOLE_Conv_TEST) - cval

boxplot(ptestl~TADPOLE_Conv_TEST$status)
ptestr <- exp(ptestl)

predsurv <- cbind(TADPOLE_Conv_TEST$TimeToEvent,
                  TADPOLE_Conv_TEST$status,
                  ptestl,
                  ptestr)

prSurv <- predictionStats_survival(predsurv,"MCI to  AD Conversion")
pander::pander(prSurv$CIRisk)
pander::pander(prSurv$CILp)
pander::pander(prSurv$spearmanCI)

prBin <- predictionStats_binary(cbind(TADPOLE_Conv_TEST$status,ptestl),"MCI to  AD Conversion")
pander::pander(prBin$aucs)
pander::pander(prBin$CM.analysis$tab)

par(op)

```


### Learning EBIC

```{r results = "asis", warning = FALSE, dpi=600, fig.height= 6.0, fig.width= 8.0}
bConvmBessE <- BESS_EBIC(Surv(TimeToEvent,status)~.,TADPOLE_Conv_TRAIN)

pander::pander(bConvmBessE$selectedfeatures)

ptestl <- predict(bConvmBessE,TADPOLE_Conv_TEST)
cval <- mean(ptestl)
ptestl <- predict(bConvmBessE,TADPOLE_Conv_TEST) - cval

boxplot(ptestl~TADPOLE_Conv_TEST$status)
ptestr <- exp(ptestl)

predsurv <- cbind(TADPOLE_Conv_TEST$TimeToEvent,
                  TADPOLE_Conv_TEST$status,
                  ptestl,
                  ptestr)

prSurv <- predictionStats_survival(predsurv,"MCI to  AD Conversion")
pander::pander(prSurv$CIRisk)
pander::pander(prSurv$CILp)
pander::pander(prSurv$spearmanCI)

prBin <- predictionStats_binary(cbind(TADPOLE_Conv_TEST$status,ptestl),"MCI to  AD Conversion")
pander::pander(prBin$aucs)
pander::pander(prBin$CM.analysis$tab)

par(op)

```


### Learning GS

```{r results = "asis", warning = FALSE, dpi=600, fig.height= 6.0, fig.width= 8.0}
bConvmBessGS <- BESS_GSECTION(Surv(TimeToEvent,status)~.,TADPOLE_Conv_TRAIN)

pander::pander(bConvmBessGS$selectedfeatures)

ptestl <- predict(bConvmBessGS,TADPOLE_Conv_TEST)
cval <- mean(ptestl)
ptestl <- predict(bConvmBessGS,TADPOLE_Conv_TEST) - cval

boxplot(ptestl~TADPOLE_Conv_TEST$status)
ptestr <- exp(ptestl)

predsurv <- cbind(TADPOLE_Conv_TEST$TimeToEvent,
                  TADPOLE_Conv_TEST$status,
                  ptestl,
                  ptestr)

prSurv <- predictionStats_survival(predsurv,"MCI to  AD Conversion")
pander::pander(prSurv$CIRisk)
pander::pander(prSurv$CILp)
pander::pander(prSurv$spearmanCI)

prBin <- predictionStats_binary(cbind(TADPOLE_Conv_TEST$status,ptestl),"MCI to  AD Conversion")
pander::pander(prBin$aucs)
pander::pander(prBin$CM.analysis$tab)

par(op)

```


### Saving the enviroment
```{r}
save.image("./TADPOLE_BESS_Results.RData")


```

